### ISSUE TITLE
Customize 404 page when deployed

### ISSUE THREAD

**Issue by jonas-jonas** [ory/docs#1074]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The current 404 page of the docs is not customized and just shows the generic vercel error page, with a link to their docs.

See here https://www.ory.sh/docs/this-does-not-exist

### Describe your ideal solution

Provide a custom 404 page with the Ory docs header and footer, and some helpful text and links back to actual content.

### Workarounds or alternatives

n/a

### Version

master

### Additional Context

https://www.ory.sh/docs/this-does-not-exist

**Comment by tomekpapiernik** [comment]
https://github.com/facebook/docusaurus/discussions/6030
