### ISSUE TITLE
upgrade APIs from swagger 2.0 to OpenAPI 3.x

### ISSUE THREAD

**Issue by cvgaviao** [ory/docs#108]
The provided API specs are in version 2.0, but most of modern tools are already moving to OpenAPI 3.x.
That are some available tool that helps a lot in such task: 
  [https://mermade.org.uk/openapi-converter](https://mermade.org.uk/openapi-converter)

**Comment by aeneasr** [comment]
Converters usually don't work very well and are buggy. OpenAPI 2.x is very well supported and unfortunately our toolchain doesn't work with OpenAPI 3.x yet -> closing.
