### ISSUE TITLE
Roll back link changes

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#1094]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

According to https://github.com/ory/docs/pull/1091#discussion_r1030275924, links in markdown files are now using relative URLs instead of file paths.

### Describe your ideal solution

Follow best-practices according to docusaurus:

> Using relative file paths (with .md extensions) instead of relative URL links provides the following benefits:
>
> * Links will keep working on the GitHub interface and many Markdown editors
> * You can customize the files' slugs without having to update all the links
> * Moving files around the folders can be tracked by your editor, and some editors may automatically update file links
> * A [versioned doc](https://docusaurus.io/docs/versioning) will link to another doc of the exact same version
> * Relative URL links are very likely to break if you update the [trailingSlash config](https://docusaurus.io/docs/api/docusaurus-config#trailingSlash)

https://github.com/ory/docs/pull/1091#discussion_r1030371701

My recommendation is to write a regex to find the links.

### Workarounds or alternatives

No workarounds.

### Version

master

### Additional Context

Codify this in the style guides and add automated tests to find these incorrect patterns.

**Comment by tomekpapiernik** [comment]
I'm still for using document IDs for linking. It's a more convenient approach. 
Let me address the points you list: 

> Links will keep working on the GitHub interface and many Markdown editors

Our docs contain many mdx codeblocks and custom imports/elements (tabs, BrowserWindow) which make them really nasty to read in GH anyway. The desired consumption mode is through ory.sh/docs Relative links with IDs still work fine in VSCode (command+click on the link to go to the linked doc).

> You can customize the files' slugs without having to update all the links

I opted for a system where we add numeric prefixes to filenames to reduce the sidebar size and make it much easier to find the document you're looking at our website in the directory structure. Additionally, filenames mirror document IDs to make linking easier - you know what to link to at a glance, w/o having to open the document you want to link to and make sure that its ID and filename match.

> Moving files around the folders can be tracked by your editor, and some editors may automatically update file links

Can't comment on that, didn't have any success with that and honestly haven't spend much time trying to get my editor to accurately reflect changes in relative links. 

> A [versioned doc](https://docusaurus.io/docs/versioning) will link to another doc of the exact same version

We don't version documents. 

> Relative URL links are very likely to break if you update the [trailingSlash config](https://docusaurus.io/docs/api/docusaurus-config#trailingSlash)

This is not something that needs adjusting on a regular basis - non-issue.

**Comment by aeneasr** [comment]
Docusaurus does not detect broken links when using URL paths when using development mode:

```
// Working link
[this document](../../kratos/guides/select-cipher-algorithm.mdx)
[this document](../../kratos/guides/select-cipher-algorithm)

// Is detected as broken link
[this document](../../kratos/guides/select-cipher-algorithm-i-do-not-exist.mdx)

// Not detected as broken link
[this document](../../kratos/guides/select-cipher-i-do-not-exist)
```

The broken links are correctly identified when creating a production build. This usually happens once people pushed their branch and see a failure in the CI, which is let's just say annoying.

**Comment by aeneasr** [comment]
@tomekpapiernik let's just do what the people who write the software recommend. The points are straight from Docusaurus docs, I did not make those up.

**Comment by aeneasr** [comment]
I understand, but I won't back down on this ;)

It happened now 3 times to me that I updated a document, the preview (`npm run start`) worked fine, but the build (in the CI) failed because of a broken link (basically what I found here: https://github.com/ory/docs/issues/1094#issuecomment-1324988495 ). So instead of fixing the problem immediately when a link breaks, there is a latency of about 30 minutes total to get the vercel preview working again:

1. Write documentation
2. Looks good, commit and push
3. Wait for CI
4. Oh it failed - investigate
5. Link was broken, fix
6. Push again
7. Hope CI passes
8. Repeat

Alternatively:

1. Write documentation
2. Kill dev server
3. Run npm run build (takes ~3 minutes)
4. See broken links
5. Run dev server
6. Fix
7. Kill dev server
8. Run build
9. Repeat
10. Commit and push

With the approach docusaurus **recommends**:

1. Write document
2. Dev server complains about broken link immediately
3. Fix
4. Done

So let's just stick to what the docusaurus team recommends, and improve this flow.

**Comment by tomekpapiernik** [comment]
Ok. The updated guidelines codify this as the way to do links in our documentation.

**Comment by aeneasr** [comment]
Nice, thank you!
