### ISSUE TITLE
Remove license headers from embedded code files

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#1103]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When embedding code

```
import CodeBlock from '@theme/CodeBlock';
import content from '!!raw-loader!../../../code-examples/getting-started/oauth2-integration/express/server.js';

<CodeBlock language="js">{content}</CodeBlock>
```

it now shows licenses headers

<img width="1122" alt="Screenshot 2022-11-29 at 12 04 44" src="https://user-images.githubusercontent.com/3372410/204513299-82d08abe-b755-4215-89b1-19bd17fbfda5.png">

as we now add license headers to all our code files.

### Describe your ideal solution

The `CodeBlock`  should automatically remove these license headers.

### Workarounds or alternatives

None

### Version

master

**Comment by CaptainStandby** [comment]
@kelkarajay Your could try to use [Custom magic comments](https://docusaurus.io/docs/markdown-features/code-blocks#custom-magic-comments) for this.
