### ISSUE TITLE
Missing images on verification docs

### ISSUE THREAD

**Issue by jonas-jonas** [ory/docs#1108]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

At some point the images on the verification docs have gone missing. 

### Reproducing the bug

Go to https://www.ory.sh/docs/kratos/self-service/flows/verify-email-account-activation#verification-link-method

### Version

master

### Additional Context

The reason why that wasn’t picked up by the Docusaurus tool chain is that they were embedded using an HTML tag `<img alt="Verification email for known address" src={useBaseUrl("images/kratos/email-verify-known.png")} />`.

To Docusaurus this is just an external embed, which they don’t check for availability during the build process (yet). As part of the ongoing documentation restructure, we should define how to embed (internal) images, that being the `![alt text](/path/to/image)` Markdown syntax.

**Comment by aeneasr** [comment]
@tomekpapiernik I think this is another one of those that got deleted

**Comment by aeneasr** [comment]
Maybe just bring them all back for now. The pain of having to find all the places where images are now broken is not worth the few MB of space they use.

**Comment by tomekpapiernik** [comment]
This doc was restructured and doesn't contain these images. It looks like there aren't any HTML image embeds in docs anymore.
