### ISSUE TITLE
Dissolve "Other" category

### ISSUE THREAD

**Issue by vinckr** [ory/docs#1127]
Move the documents in the "Other category" somewhere where users can find them. 

My proposal: 

- Make 
Ory CLI 
a top level category 

Alternative: Top Menu Bar, next to API, but it is getting crowded there

- Custom UI w/ Ory Elements (or full: Learn how to create custom TypeScript SPA with Ory Elements)
~Rename to "TypeScript SPA with Ory Elements" in the sidebar and~ put under Quickstart/Login. 

Alternative: Rename to "TypeScript SPA" and add under a "Ory Elements/Elements" Quickstarts category

- Terminology
This document can be dissolved in "Introduction" and other introductory documents i.e. the terms should be explained in the first document you read where the term is used

Alternative: Move to Troubleshooting? Or after Introduction? It could also fit in a reference category. 

- Browser redirects and flow completion

Move to "self-service/flows/", as it only concerns the identities part and self-service flows

Alternative: Move somewhere else prominently in the Identities and sessions section.

**Comment by aeneasr** [comment]
This is a temporary section, restructure according to the plan in notion please :)
