### ISSUE TITLE
Oathkeeper links broken

### ISSUE THREAD

**Issue by jeroenpeeters** [ory/docs#12]
I cannot navigate to any topics under [https://www.ory.sh/docs/guides/latest/oathkeeper/](https://www.ory.sh/docs/guides/latest/oathkeeper/) . The links are broken.

**Comment by arekkas** [comment]
Please use, for now, the latest stable release of oathkeeper and the docs which is at https://www.ory.sh/docs/guides/v0.11.12/

You can select the version here:

![image](https://user-images.githubusercontent.com/3372410/40184122-ba47967a-59ef-11e8-8548-8691e048fa90.png)

**Comment by arekkas** [comment]
this is now resolved by having a latest branch (stable) and a master branch (unstable) with the default being stable selected
