### ISSUE TITLE
Ory/client(1.1.7) User logout example not working

### ISSUE THREAD

**Issue by SagaGG** [ory/docs#1234]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

this example is not working:
https://www.ory.sh/docs/kratos/self-service/flows/user-logout#server-rendered-browser-applications

ory.createBrowserLogoutFlow(req.cookies["ory_kratos_session"]) `change to` ory.createBrowserLogoutFlow({
      cookie: req.header("cookie"),
    });

then it's working.

it takes me hours to resolve this issue.

### Reproducing the bug

just follow the official example code.

### Version

ory/client 1.1.7

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

None

**Comment by jonas-jonas** [comment]
Thanks for the report, and sorry for your troubles. The docs are still a little bit of work in progress and some code examples aren't 100% there yet. We will fix this issue shortly. But contributions are always welcome.
