### ISSUE TITLE
Example to Use Admin UI Doesn't Compile

### ISSUE THREAD

**Issue by russoj88** [ory/docs#1301]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The example here does not compile: https://www.ory.sh/docs/kratos/sdk/go#use-admin-api

@vinckr following up from our Slack conversation.

### Reproducing the bug

Copy the code and try to compile with go 1.20

### Version

v1.1.21

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other

**Comment by vinckr** [comment]
Hello @russoj88 
I have since made some updates to the examples. 
Can you check again please? 
Admin API examples has been moved to here: https://www.ory.sh/docs/kratos/sdk/go#use-identity-management-api

**Comment by russoj88** [comment]
Yes, that compiles now.

Thanks @vinckr !

**Comment by vinckr** [comment]
great :)
FWIW here are more examples: https://github.com/ory/docs/tree/master/code-examples/sdk 
(I will add them directly to the sdk examples as well soon, just need to figure out a good testing strategy)
