### ISSUE TITLE
Email `code` strategy needs more explanation in the docs 

### ISSUE THREAD

**Issue by Benehiko** [ory/docs#1308]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The docs do not explain why the verification `code` flow gives both the `.VerificationCode` and `.VerificationURL`, but the `.RecoveryCode` and `RecoveryURL` only gives access to the code and not a URL like with verification.

The reason for recovery not getting the URL as well is due to the URL being shared / intercepted and the session being hijacked (?) /cc @jonas-jonas 

Since the Recovery flow is a more high-risk operation giving access to a session, the code needs to be entered manually by the user. The Verification flow does not give access to a session so is low-risk.

http://localhost:3000/docs/kratos/emails-sms/custom-email-templates

### Describe your ideal solution

A document describing in detail why the recovery `code` method only gives a code and not a URL with the code.

### Workarounds or alternatives

None

### Version

latest

**Comment by jonas-jonas** [comment]
>The reason for recovery not getting the URL as well is due to the URL being shared / intercepted and the session being hijacked (?) /cc @jonas-jonas

It's because the flow is protected against CSRF attacks. If we include a link, we can no longer do that. User's would have to open the link in the same browser and immediately after initiating recovery, without doing/visiting other flow pages.

>A document describing in detail why the recovery code method only gives a code and not a URL with the code.

A whole document is a bit overkill. But I guess a section in https://www.ory.sh/docs/kratos/self-service/flows/account-recovery-password-reset and on the email templates page would help. Agreed.
