### ISSUE TITLE
Page missing from sidebar

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#1389]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Page missing from sidebar

### Reproducing the bug

Go to https://www.ory.sh/docs/hydra/login-consent-flow

### Version

-

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by vinckr** [comment]
Seems we have this instead: https://www.ory.sh/docs/oauth2-oidc/custom-login-consent/flow

Should we just add the steps to the end (above the sequence diagram) and delete/redirect this page?
