### ISSUE TITLE
API documentation is missing

### ISSUE THREAD

**Issue by JohnDuncanScott** [ory/docs#1489]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Go to https://www.ory.sh/docs/hydra/reference/api. There used to be documentation here. The entire page is blank, probably since the last edit on 27th July 2023. It doesn't appear to have migrated elsewhere. In addition the search box in the top right of the page cannot be used - click it highlights it but no text can be typed in.

### Reproducing the bug

Bug 1:

- Go to https://www.ory.sh/docs/hydra/reference/api
- Expect: API docs
- Actual: No API docs

Bug 2:

- Go to any doc page, e.g. https://www.ory.sh/docs/oauth2-oidc
- Try searching using the search box in the top right of the page
- Expect: To be able to search
- Actual: Search box highlights but can't type any text (using Edge)

### Version

N/A

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

None

**Comment by kmherrmann** [comment]
Sorry about the issue, a CDN cache was biting us. Should be all back up - thanks for the report!

**Comment by aeneasr** [comment]
This isn't really resolved because the underlying issue isn't fixed. I'll reopen this until it is!

**Comment by vinckr** [comment]
should be fixed now
