### ISSUE TITLE
lookup_secret label wrong in API docs

### ISSUE THREAD

**Issue by vinckr** [ory/docs#1635]
When deleting a lookup secret via the REST API the docs say you need to set the path parameter to lookup , but it should in fact be lookup_secret
![Screenshot 2024-01-25 at 15 13 21](https://github.com/ory/docs/assets/55394283/a2c1dd7e-5763-43a2-b81c-90e636d37993)

**Comment by alnr** [comment]
This is fixed (but the generated output is ugly).
