### ISSUE TITLE
oathkeeper: update judge/decisions endpoint in swagger docs for OS12

### ISSUE THREAD

**Issue by hefekranz** [ory/docs#171]
Hi there, (again with right account :)
the oathkeeper docs for OS12 reflect the current state of 0.16, but the swagger api docs still state the /judge instead of the new /decision endpoint. This took me a bit to realize, since it is only mentioned in the upgrade docs, so maybe this should be updated :)
If you point out docs or recipe on how to regenerate, I'd be happy to do this myself.
Cheers and thanks for the great tool!
Ref:
https://www.ory.sh/docs/oathkeeper/sdk/api

**Comment by aeneasr** [comment]
Interesting, the Swagger definition is properly defined (see https://github.com/ory/oathkeeper/blob/master/api/decision.go#L67 ) but it seems that the changes have not propagated through the CI to this repo. I'll take a look at it soon.

**Comment by aeneasr** [comment]
This is now resolved!
