### ISSUE TITLE
bug: `/docs/kratos/bring-your-own-ui/custom-ui-overview` broken

### ISSUE THREAD

**Issue by meysam81** [ory/docs#1857]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

The URI mentioned in the title is broken.

Here's a screenshot of the page as of Sep 1, 2024 :point_down: 

![Screenshot from 2024-09-01 10-59-34](https://github.com/user-attachments/assets/3477f417-3e83-44be-a5dc-c51c0a0858fe)

### Reproducing the bug

Navigate to <https://www.ory.sh/docs/kratos/bring-your-own-ui/custom-ui-overview>

### Version

latest

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other

### Additional Context

This line has changed at Aug 30, 2024 :point_down: 

https://github.com/ory/docs/blob/1f8f7d22c978bad62af8733bc4d699e246ff9a4f/docs/kratos/bring-your-own-ui/01_overview.mdx?plain=1#L2

**Comment by aeneasr** [comment]
Thank you for the report! We will fix it asap

**Comment by meysam81** [comment]
@aeneasr 

Your welcome.

I've got my CI to thank for :hugs: ([ref](https://github.com/developer-friendly/blog/actions/runs/10652401477/job/29526186510#step:5:569)).

**Comment by aeneasr** [comment]
fixed
