### ISSUE TITLE
OAuth2 revoke endpoint documentation needs improvement

### ISSUE THREAD

**Issue by ngrigoriev** [ory/docs#199]
I think that the /oauth/revoke endpoint documentation could be improved. I have found that:

- if the client is not public, then one MUST use the client ID and secret. It seems the oauth2 authentication mentioned there is an option at all.
- if the client is public, then it is an opposite - since there is no password, then basic authentication is not an option. But then it seems that the client MUST send "cliend_id" form field or it will fail

By the way, I have tested all this with JWT token, not the opaque one. Maybe the behavior is even more complex.

**Comment by aeneasr** [comment]
Oh yeah absolutely - woudl you be up for a PR? :)
