### ISSUE TITLE
Why is this a good practice?

### ISSUE THREAD

**Issue by dopry** [ory/docs#201]
in https://github.com/ory/docs/blob/master/docs/oathkeeper/configure-deploy.md#dockerfile there is a statement, "It would also be possible to mount the directory instead, but adding these definitions to the Dockerfile itself and making the build process a part of your CI pipeline is considered good practice!"

Who says it is a good practice to embed configuration and keypairs in an image? A lot of people would consider it a bad practice. Many people who work in container space treat them as simple binaries and execution environments while configuration remains a concern of the orchestration engine.  That way a binary can be promoted across many configurations from dev, integration, uat, and prod without changes.  In addition, putting sensitive assets like the jwk key pair in revision control or outside of a secured operating environment seems like a patently bad and insecure approach.  Contrary to your unsupported recommendation, creating the files in a secured volume that your orchestration engine can mount to the container at runtime seems like it would be the better approach given the potential security sensitivity of the access control configuration and signing key pair.  

Again, who says embedding this configuration in your container image is a good idea? Do they have counter-arguments to the concerns I've raised?

**Comment by aeneasr** [comment]
Yeah, this definitely changed with Kubernetes and it makes sense to update this section accordingly. Would you be up for it?

**Comment by dopry** [comment]
I don't think K8s has much to do with it. Containers are a form of packaging that just happens to include most of the execution context. The general notion that you shouldn't embed production config or credentials in packaging pre-dates K8s by a few decades.

I'll try to take a stab at re-writing those docs. I've got a lot on my plate, ping this issue again if I don't get a PR up, in the next two weeks or so.
