### ISSUE TITLE
Side nav scrolls back to top when a link is clicked

### ISSUE THREAD

**Issue by henryjw** [ory/docs#237]
**Expectation**
When I click on a link on the side nav, the side nav should keep the position.

**Actual**
The side nav resets to the top when a link is clicked.

<img width="1676" alt="ory ui" src="https://user-images.githubusercontent.com/3443648/71523447-1f635e00-2897-11ea-9d8a-f64619f4ce65.png">

**Comment by aeneasr** [comment]
Thank you for the report - that is indeed very annoying!

We're currently still using Docusaurus 1.x where this behavior is difficult to fix (at least I don't know an easy solution). But I think they solved that with Docusaurus 2.x which we will upgrade to once it's no longer in alpha!

**Comment by aeneasr** [comment]
Closing since we have docusaurus v2 now.
