### ISSUE TITLE
Docs localhost website creator script broken

### ISSUE THREAD

**Issue by tacurran** [ory/docs#251]
When trying to install and run the local version of the static documentation, the script fails to execute.
From the readme.md...
"To run a local preview:
$ cd website
$ npm install
$ npm run start
The script should open a browser with http://localhost:3000/docs for you."
after starting the script using npm run start, the error appears to be in the "docusaurus-start"
9 verbose lifecycle @~start: CWD: /Applications/GoLand.app/Contents/bin/git@github.com:ory/docs/website
10 silly lifecycle @~start: Args: [ ‘-c’, ‘docusaurus-start’ ]
11 info lifecycle @~start: Failed to exec start script
12 verbose stack Error: @ start: `docusaurus-start`

**Comment by aeneasr** [comment]
Is there maybe already something running on port 3000? You can find all open ports using:

```
netstat -ap tcp | grep -i "listen"
```

or (works better on macos)

```
sudo lsof -PiTCP -sTCP:LISTEN
```

Maybe there's a docker image running - you can kill all docker images using: `docker kill $(docker ps -q)`

**Comment by tacurran** [comment]
I am using Goland IDE via the VCS/Get from version control menu. The repository clone is:
git@github.com:ory/docs.git
So the "docusaurus" script breaks down in the PATH definition (see below).
## This issue was resolved as follows:
1. change the path from ...git@github.com:ory/docs/website... to ...git@github.comory/docs/website...
2. run the npm install from the new directory
3. the browser should point to localhost:3000

## extract from log
8 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Applications/GoLand.app/Contents/bin/git@github.com:ory/docs/website/node_modules/.bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/go/1.13.6/libexec/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/thomas/.go/bin:/usr/local/opt/go/libexec/bin:/Users/thomas/.go/bin:/usr/local/opt/go/libexec/bin
9 verbose lifecycle @~start: CWD: /Applications/GoLand.app/Contents/bin/git@github.com:ory/docs/website
10 silly lifecycle @~start: Args: [ '-c', 'docusaurus-start' ]
11 info lifecycle @~start: Failed to exec start script
12 verbose stack Error: @ start: `docusaurus-start`
<EOM>
