### ISSUE TITLE
add tips to generate the SDK for other languages

### ISSUE THREAD

**Issue by zepatrik** [ory/docs#309]
Some people might want to generate the SDK for some language we do not provide. One example is @alampros who uses a self generated C# SDK.
Adding a page with FAQs and tips around SDK generation would be a good idea.
Let's start off with collecting these tips in this issue.

**Comment by vinckr** [comment]
https://github.com/ory/hydra/issues/2017

**Comment by vinckr** [comment]
- Improve documentation here: https://www.ory.sh/kratos/docs/sdk/

- [ ] Python SDK documentation
- [ ] PHP SDK documentation
- [ ] Go SDK documentation
- [ ] NodeJS (with TypeScript) SDK documentation
- [ ] Java SDK documentation
- [ ] Ruby SDK documentation

**Comment by vinckr** [comment]
Phew it has been a while 😅 

Should we still add this @zepatrik ? 
I think most people would struggle to use a self generated SDK - and those who are able to make use of it probably would be able to figure out the generation for themselves. 

I also feel the whole SDK process is too unstable to really document this as a "feature" to generate your own SDKs. 
I think we should just gather feedback on what SDKs people are missing and then see how we can make them available. 

### How to generate Ory SDKs

Generating Ory SDKs is a multi-step process. Have a look at the make sdk task for details, for example in Ory Kratos:
https://github.com/ory/kratos/blob/aee2b1ed1189b57fcbb1aaa456444d5121be94b1/Makefile#L81
We generate the OpenAPI 2 schema first from comments in the code and then migrate it to v3.
In the end we use spec/api.json to generate the official clients, for example for Ory Kratos. https://github.com/ory/kratos/blob/aee2b1ed1189b57fcbb1aaa456444d5121be94b1/Makefile#L104-L111
