### ISSUE TITLE
Include Kratos in projects.md

### ISSUE THREAD

**Issue by vinckr** [ory/docs#366]
In [Ecosystem](https://github.com/ory/docs/blob/master/docs/docs/ecosystem/projects.md) an soon-to-be-announced identity management server is mentioned. 
We should update the section to include Kratos with some examples like the other projects. 
I think the text is not bad otherwise, so just a small update would fix it here.

The graphic also needs the updated logos (and maybe the colours of each project?) @jfcurran.

**Comment by aeneasr** [comment]
Yes absolutely!
