### ISSUE TITLE
docs: hydra guide to skip consent redirection

### ISSUE THREAD

**Issue by vinckr** [ory/docs#418]
as per https://github.com/ory/hydra/discussions/2562

**Comment by vinckr** [comment]
Perfect yes 🙏 

If you could walk me through the feature or record a short screencast for it, I can write the docs. Or you create a draft and I review, whatever fits you better right now @hperl

**Comment by hperl** [comment]
@vinckr I am unsure where that content fits best. It is just a single flag added to the client configuration named `skip_consent`. In the Console, you can easily toggle this:

Skip consent off:

![Screenshot from 2023-03-02 14-34-24](https://user-images.githubusercontent.com/34397/222448973-3e718c62-efa6-42d7-811b-56902d1bd4f2.png)


Skip consent on:

![Screenshot from 2023-03-02 14-34-08](https://user-images.githubusercontent.com/34397/222449032-ecc3f030-c774-43a2-a9a9-670d46364497.png)


The CLI should have the same flag, but changes still need to propagate here.

**Comment by vinckr** [comment]
Closing since this is now documented here:

One small question @hperl , I could not find the setting in here: https://www.ory.sh/docs/hydra/reference/configuration ; do you know why, is it still on master?
