### ISSUE TITLE
Services and Apis sidebar button hides

### ISSUE THREAD

**Issue by Benehiko** [ory/docs#471]
https://www.ory.sh/docs/concepts/services-api

The sidebar hides when expanding a button group listed above it

https://user-images.githubusercontent.com/18033717/130452312-a7a698b9-77d6-47dd-8fb9-278b3ca34244.mov

**Comment by Benehiko** [comment]
This seems to not only be related to the services & apis pages.

https://user-images.githubusercontent.com/18033717/133616126-49061a81-c5a7-4901-9dfb-1b2240ebff70.mov

**Comment by aeneasr** [comment]
Probably makes sense to report this over at: https://github.com/facebook/docusaurus :)
