### ISSUE TITLE
[Ory Hydra] Logout Flow image is outdated

### ISSUE THREAD

**Issue by GLOFonseca** [ory/docs#514]
The following image is outdated:
![image](https://user-images.githubusercontent.com/18470453/143094775-19dc1630-3ebf-448a-90ef-5e8cf19243c8.png)
Source: https://www.ory.sh/hydra/docs/concepts/logout/

There are some requests parameters that are not with the current name expected like `logout_verifier` should be `logout_challenge`.

**Comment by aeneasr** [comment]
Oh, thank you for raising this issue! Would you be open to resolve these? There's an edit button on the page .)

**Comment by GLOFonseca** [comment]
Hello @aeneasr, I have created a Pull Request changing this diagram. Some checks are falling, can you review them?
https://github.com/ory/hydra/pull/2892

**Comment by aeneasr** [comment]
Thank you! Closing this as we now have a PR for it.
