### ISSUE TITLE
Codeblock formatting breaks when hovering over the sidebar

### ISSUE THREAD

**Issue by frederikhors** [ory/docs#520]
![image](https://user-images.githubusercontent.com/41120635/126538931-205caefe-42c7-49f0-9786-a05f5bfe6db7.png)

**Describe the bug**

Sometimes this is the docs site.

I'm on Windows 10 - Chrome 91.0.

Why?

**Reproducing the bug**

I cannot reproduce.

Sometimes if I click two times on some text, copy it, change window, come back on docs site, here it goes!

**Comment by vinckr** [comment]
Moving the issue to https://github.com/ory/docs/ as it is most likely a bug in here or in https://github.com/ory/docusaurus-template/.

**Comment by aeneasr** [comment]
Thhis is still an issue!

**Comment by aeneasr** [comment]
@zeropaper if you have some time some day can you please take a look at this? This is still an issue in the new docs as well

**Comment by zeropaper** [comment]
I will try to reproduce...

**Comment by aeneasr** [comment]
I had luck reproducing it by moving the mouse around the nav.

I think the problem is that something is being updated in the DOM and then prismjs loses authority over the code box for some reason and does not recompute

**Comment by zeropaper** [comment]
It took me a while to find the page and reproduce, but yes, I can. With a hover on the sidebar too.

**Comment by vinckr** [comment]
Since this is still an issue I changed the title to something more descriptive.
I loved the original title, but it was hard to know what this is about 😁

**Comment by vinckr** [comment]
https://github.com/rohit-gohri/redocusaurus/issues/89#issuecomment-942256382
https://github.com/facebook/docusaurus/issues/5443

**Comment by aeneasr** [comment]
Finally, it has been resolved!

**Comment by aeneasr** [comment]
The problem is back
