### ISSUE TITLE
How to version config + REST API

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#570]
We need to version the config reference and REST API. How do we achieve that?

**Comment by vinckr** [comment]
Maybe under "Reference" -> "Versioned Configuration" / "Versioned HTTP API"
+ 
add a notice to the latest "Configuration" / "HTTP API" 

>This reference configuration/API documentation is for Ory Kratos version x.xx, for older version please visit [this document](./versioned-configuration.md)"
