### ISSUE TITLE
Show YAML output next to JSON Schema Config Editor

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#572]
As people create a yaml config using this generator, they should see right of it the YAML output so that they can copy paste it to their own config

<img width="2672" alt="Screenshot 2022-02-10 at 23 42 10" src="https://user-images.githubusercontent.com/3372410/153509343-df0eb772-69b5-40c1-9d92-df7307caa34c.png">

**Comment by zeropaper** [comment]
@aeneasr I was giving that a shot (it took me a little while to realize that the editor is only on the `json-schema` branch) and stumbled upon a potential hairy problem...
![image](https://user-images.githubusercontent.com/65971/153543211-93c70660-ee93-4db4-a5ca-63432ee7427b.png)

I suspect that the editor is still a work in progress. Whatever I try to change, it ends up in a error.

The docusaurus theme uses CSS `!important` keyword... There's maybe a way around that (I'm going to dig deeper the docusaurus docs and code...), but that's... a serious bummer (to phrase it politely)

**Comment by zeropaper** [comment]
I didn't look at the cause of the error
Makes sense :)
