### ISSUE TITLE
Run your own server - Validate the OAuth2 Access Token - deprecated flag warnings for client-id and client-secret

### ISSUE THREAD

**Issue by lancegliser** [ory/docs#589]
The docs at for [Validate the OAuth2 Access Token](https://www.ory.sh/run-oauth2-server-open-source-api-security/#validate-the-oauth2-access-token) use this format:

```
docker run --rm -it \
  --network hydraguide \
  oryd/hydra:v1.10.2 \
  token introspect \
    --client-id some-consumer \
    --client-secret some-secret \
    --endpoint http://ory-hydra-example--hydra:4445 \
    >INSERT-TOKEN-HERE<
```

It's usage results in this output:

```
Flags --client-id and --client-secret and environment variables OAUTH2_CLIENT_SECRET and OAUTH2_ACCESS_TOKEN are deprecated and have no longer any effect.{
        "active": true,
        "aud": null,
        "client_id": "CCF",
        "exp": 1645464515,
        "iat": 1644859715,
        "iss": "http://localhost:4444/",
        "sub": "CCF",
        "token_type": "access_token"
}
```

Running with the client id and secret removed return inspection perfectly. I looked, but I don't see that page as part of the documentation doing a quick search for "The result will be an OAuth2 access token that will be used to validate in the next step."

**Comment by aeneasr** [comment]
Thank you! You can simply omit these values :) We will remove it from the docs page!
