### ISSUE TITLE
Search results are inconsistent

### ISSUE THREAD

**Issue by zeropaper** [ory/docs#600]
I was look for some information regarding the SDK (`ORY_SDK_URL` to be more precise) and tried to search with using the field at the top of the page.

**Steps to reproduce**

1. Try searching for something using the field at the top right of the page

**Expected behavior**

I see at least some results in the modal dialog.

**Observed behavior**

Nothing could be find.
![image](https://user-images.githubusercontent.com/65971/154249908-af882955-2641-4578-9cf1-7a3efdad6591.png)

However, if searching from the "search page" (https://ory.sh/docs/search), I'm getting some results.
![image](https://user-images.githubusercontent.com/65971/154250171-48be77ab-f69a-4bab-ba2b-53b64995740b.png)

**Comment by aeneasr** [comment]
Fixes welcomed!

**Comment by aeneasr** [comment]
I can share access with Algolia if needed
