### ISSUE TITLE
docs: Text version of 'design complex authorization with Ory Keto' 

### ISSUE THREAD

**Issue by gen1us2k** [ory/docs#636]
From February slack harvest

https://www.ory.sh/summit/2021/design-complex-authz/

**Comment by vinckr** [comment]
I can take this one ✋

**Comment by vinckr** [comment]
subtitles done, next need to grok the example a bit more and write a new text.

**Comment by vinckr** [comment]
will be closed by https://github.com/ory/web/pull/606

**Comment by vinckr** [comment]
closing this now, since the method/workaround is outdated now with userset rewrites, so no need to publish the blogpost, see linked issue.
