### ISSUE TITLE
Suggest use of mkcert

### ISSUE THREAD

**Issue by mitar** [ory/docs#649]
See: https://github.com/FiloSottile/mkcert

I am reading [this guide](https://www.ory.sh/docs/hydra/configure-deploy) and maybe instead of suggesting to people to ignore TLS errors, it would be more useful to tell them about mkcert and also teach them at the same time how you give provide TLS certificate to Hydra. Developers can then use that knowledge in production, too.

Not to mention that then local development experience really matches production.

**Comment by mitar** [comment]
Yes. Or at least to include it in the guide as an alternative.

**Comment by gen1us2k** [comment]
Hello @mitar. Thanks for your suggestion. I tried to update [this guide](https://www.ory.sh/docs/hydra/configure-deploy) and add mkcert.
```sh
mkcert -install
Created a new local CA 💥
The local CA is now installed in the system trust store! ⚡️
The local CA is now installed in the Firefox trust store (requires browser restart)! 🦊

mkcert localhost 127.0.0.1 ory-hydra-example--hydra

Created a new certificate valid for the following names 📜

 - "localhost"
 - "127.0.0.1"
 - "ory-hydra-example--hydra"

The certificate is at "./localhost+2.pem" and the key at "./localhost+2-key.pem" ✅

```

Then I setup required env variables
```sh
export SERVE_TLS_CERT_BASE64=$(base64 -i ./localhost+2.pem)
export SERVE_TLS_KEY_BASE64=$(base64 -i ./localhost+2-key.pem)
```

Then I run hydra using docker and I have a valid SSL connection for `https://localhost:9000`.

But anyway we still need `--skip-tls-verify` option for `Perform Oauth2 flow`
```
~ docker run --rm -it \
  -e HYDRA_ADMIN_URL=https://ory-hydra-example--hydra:4445 \
  --network hydraguide \
  oryd/hydra:v1.10.6 \
  clients create  \
    --id facebook-photo-backup \
    --secret some-secret \
    --grant-types authorization_code,refresh_token,client_credentials,implicit \
    --response-types token,code,id_token \
    --scope openid,offline,photos.read \
    --callbacks http://127.0.0.1:9010/callback
You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
The request failed with the following error message:
Post "https://ory-hydra-example--hydra:4445/clients": x509: certificate signed by unknown authority
```

It just adds additional steps and generates issues using it and we still need `--skip-tls-verify` param

**Comment by vinckr** [comment]
As there is no easy way to solve this, I am closing this for now. 
Would still love to know your thoughts on it @mitar.

**Comment by mitar** [comment]
Hm, I think this is fine? So my goal of using mkcert was to not suggest for users that they have to accept invalid certificates. Other tools besides a browser might still need exceptions, like your client-inside-docker-container example above. I think removing the browser from the exceptions list is already an improvement.
