### ISSUE TITLE
Why remapping ports

### ISSUE THREAD

**Issue by mitar** [ory/docs#651]
Reading [this documentation](https://www.ory.sh/docs/hydra/configure-deploy#deploy-ory-hydra):

I see:

```
 docker run -d \
  --name ory-hydra-example--hydra \
  --network hydraguide \
  -p 9000:4444 \
  -p 9001:4445 \
  -e SECRETS_SYSTEM=$SECRETS_SYSTEM \
  -e DSN=$DSN \
  -e URLS_SELF_ISSUER=https://localhost:9000/ \
  -e URLS_CONSENT=http://localhost:9020/consent \
  -e URLS_LOGIN=http://localhost:9020/login \
  oryd/hydra:v1.10.6 serve all
```

Can I understand why you map ports to different numbers? Why not `9000:9000` or `4444:4444`? So if one port is preferred than just use it everywhere. Otherwise debugging is tricky because you have to remember where you are connecting to.

**Comment by mitar** [comment]
Related: https://github.com/ory/hydra/pull/3027

**Comment by aeneasr** [comment]
Because that prevents conflicts with a locally running hydra server, and the docker version of it. Due to the way docker works, on some platforms, it does not realize that the port is used already and you get very strange behavior. We had a couple of questions about this in the past and decided to remap the ports to avoid this.

**Comment by mitar** [comment]
Could I suggest remapping then to something similar, like `5444:4444`?

And of course, documenting this somewhere?

**Comment by aeneasr** [comment]
I suggest touching this only to resolve an issue many users are facing. Updating the port mappings is a lot of work that needs to be done across multiple repositories to achieve consistency. It also means going through every guide this has implicit effects on and ensuring everything works.

**Comment by mitar** [comment]
OK, you have one user here who got confused by this and had issues connecting. :-)

**Comment by aeneasr** [comment]
Point taken ;)
