### ISSUE TITLE
add CTA for free Ory Cloud plan to documentation pages  

### ISSUE THREAD

**Issue by BlueAcidFrog** [ory/docs#660]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Increase visibility for our Ory Cloud free plan in documentation

### Describe your ideal solution

Adding a visible CTA (not banner) to the following sections with most traffic  
<img width="343" alt="Bildschirmfoto 2022-03-11 um 12 12 23" src="https://user-images.githubusercontent.com/89905002/157856895-ee036835-7faa-4a65-b1b0-86c3df913b24.png">

### Workarounds or alternatives

Increase visibility for existing banner:  
- remove the option to remove the banner 
- add stickiness to banner 
- increase in size 

### Version

Documentation

**Comment by aeneasr** [comment]
@BlueAcidFrog the pages `hydra/reference/api` do not have the most views, those are those who have this analytics bug, if you remember?

You need to sort  by "unique session"

**Comment by BlueAcidFrog** [comment]
@aeneasr true (: following based on users
<img width="356" alt="Bildschirmfoto 2022-03-11 um 12 47 21" src="https://user-images.githubusercontent.com/89905002/157866044-1811ad58-b99d-4800-90b5-3fce8c537e4c.png">

**Comment by vinckr** [comment]
We already have a CTA on all pages, the announcement banner at the top.
