### ISSUE TITLE
Kratos Zero Trust with IAP Proxy guide demo - "An error occurred" at /auth/login

### ISSUE THREAD

**Issue by king-trajector** [ory/docs#672]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Steps to reproduce:

1. Follow the instructions in https://www.ory.sh/docs/kratos/guides/zero-trust-iap-proxy-identity-access-proxy
```sh
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.8.0-alpha.3
docker-compose \
  -f quickstart.yml \
  -f quickstart-oathkeeper.yml \
  up --build --force-recreate
```

2. Open your web browser and go to `http://127.0.0.1:4455/dashboard`
3. You will be redirected to `http://127.0.0.1:4455/auth/login`

Expected result: The [kratos-selfservice-ui-node](https://github.com/ory/kratos-selfservice-ui-node) `/auth/login` web page
ACTUAL result: "An error occurred" (HTTP 404 response)

Ping: @gen1us2k

### Reproducing the bug

Follow the instructions in https://www.ory.sh/docs/kratos/guides/zero-trust-iap-proxy-identity-access-proxy

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by gen1us2k** [comment]
Hello @king-trajector. Thanks for opening the issue. Yep, it was fixed in the related pull request. Try to use the master branch. It has the correct version of config files.

**Comment by vinckr** [comment]
Closing since this seems fixed 👍
