### ISSUE TITLE
Explain how to use Ory with Vercel without NextJS

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#681]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

All you need to do is to port this doc

https://github.com/ory/integrations/tree/v0.2.5#vercel

to here

### Describe your ideal solution

A page in the docs which describes how to use Ory + Vercel. This would then work for Gatsby, Docusaurus, ... hosted on Vercel!

### Workarounds or alternatives

none

### Version

-

**Comment by aeneasr** [comment]
@tomekpapiernik this would be a good document to work on for you

**Comment by tokict** [comment]
@aeneasr The Ory with NextJS and Vercel tutorial is not working. Its missing ```dontUseTldForCookieDomain: true``` in order to even load your UI which is mentioned nowhere. And you need it for non custom domain vercel deployments.
I had to go to your example code in git to figure this out. Just following your tut, after deployment you are left with a broken login

**Comment by aeneasr** [comment]
Thank you @tokict for letting us know. Can you please point to the URL of the guide you followed?

**Comment by tokict** [comment]
@aeneasr I found it here: https://www.ory.sh/docs/getting-started/integrate-auth/nextjs

**Comment by aeneasr** [comment]
You're right, thank you so much, I'll update the docs here :) :)
