### ISSUE TITLE
Concept Document MFA / 2FA

### ISSUE THREAD

**Issue by vinckr** [ory/docs#687]
https://www.ory.sh/docs/kratos/self-service/flows/2fa-mfa-multi-factor-authentication

>This feature is a work in progress and is being tracked in [issue #26](https://github.com/ory/kratos/issues/26).

This page has been empty for some time, I dont think it is tracked anywhere.

**Comment by lancegliser** [comment]
The docs at: https://www.ory.sh/docs/kratos/guides/two-factor-authentication-2fa-mfa appear to up to date and discuss implementations.

**Comment by vinckr** [comment]
This seems to be fixed now. We still need an quickstart example for MFA, but that is a different issue IMO.
