### ISSUE TITLE
Streamline how we talk about config paths

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#714]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Configuration keys come in many forms! At the root there is always a JSON object:

```
{
  "some": {"key": true}
}
```

or in yaml:

```
some:
  key: true
```

Some tools like gjson and jq use the dot notation to access these keys:

```
echo '{"some": {"key": true}}' | jq -r '.some.key'
```

however, we also use the JSON Path notation for e.g. JSON Patches (this is what we use in the CLI):

```
{
  "op": "remove",
  "path": "/some/key"
}
```

### Describe your ideal solution

We should define one notation of working. I think JSON Path would be the best as we will use it everywhere where we use the Ory CLI to explain how configuration works.

The problem with JSON Path though is that it is not possible to differentiate between url paths and JSON paths.

This is a URL path:

```
/session/whoami
```

This is a config path:

```
/session/whoami/required_aal
```

so it can become quite confusing.

Let's define one standard on the documentation and try to follow it everywhere!

### Workarounds or alternatives

Keep the current mixture and explain this in some FAQ, at the risk of conusing users.

Alternatively we could also convert dot notation to JSON Path notation in the Ory CLI so that we use dot notation everywhere.

### Version

master

**Comment by vinckr** [comment]
Personally I find the JSON path notation highly confusing.
So IMO if we could use dot notation everywhere that would be ideal.
