### ISSUE TITLE
Unable to scroll.

### ISSUE THREAD

**Issue by bweston92** [ory/docs#720]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When attempting to scroll on any documentation web page it moves be back up.

### Reproducing the bug

unknown

### Version

n/a

### On which operating system are you observing this issue?

Linux

### Additional Context

```text
Google Chrome: 99.0.4844.82 (Official Build) (64-bit)
Revision: 8cc9edbaf13103187928be09721d5119481f9dc8-refs/branch-heads/4844_74@{#3}
OS: Linux
JavaScript: V8 9.9.115.9
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
```

However if I remove a scroll event listener that is on `document` element it works fine.

**Comment by bweston92** [comment]
https://user-images.githubusercontent.com/1764057/160455958-201b5ce8-e0e3-4adf-b3b0-a970f8787bda.mp4

**Comment by aeneasr** [comment]
That is quite interesting, I tried reproducing this on Chrome on macOS but could not. Maybe someone with a Linux machine can investigate?

**Comment by bweston92** [comment]
Yeah I tried to go on the documents before and had the same issues. https://mobile.twitter.com/OryCorp/status/1496060530565562371

**Comment by vinckr** [comment]
Hey Bradley, 
gutted that you are still facing this issue...

Could it be some browser extension that is causing trouble maybe - could you check with a Chrome without extensions 🙏 

Did you enable `chrome://flags/#enable-experimental-web-platform-features` by any chance? (going by [this issue](https://github.com/facebook/docusaurus/issues/6587))

**Comment by vinckr** [comment]
stale
