### ISSUE TITLE
Ory Cloud Sessions page has incorrect instructions on admin capabilities

### ISSUE THREAD

**Issue by Benehiko** [ory/docs#738]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Ory Cloud documentation on Session management is incorrect. The guide suggests that sessions can be refreshed from an admin endpoint, but they can only be extended.

https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions

Please also take a look at the handler in Kratos:

https://github.com/ory/kratos/blob/master/session/handler.go#L48-L73

### Reproducing the bug

1. Go to the Ory Docs page https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions
2. Try refresh a session as suggested in the documentation

```shell
curl https://<slug>.projects.oryapis.com/admin/sessions/40f83b8b-4f15-48eb-8c27-ff75c60757d8/refresh -H "Authorization: Bearer ory_pat_x"    
404 page not found
```

### Version

master

### On which operating system are you observing this issue?

Ory Cloud

### In which environment are you deploying?

Ory Cloud

**Comment by Benehiko** [comment]
@tomekpapiernik we should get this fixed. I see also the formatting of the guide isn't right.

**Comment by tomekpapiernik** [comment]
Let me know what the call should look like and I'd be happy to update it. 
I'm not sure what you mean by `formatting of the guide isn't right`, though. Elaborate, please?

**Comment by Benehiko** [comment]
It looks like the formatting issue was fixed in this commit

https://github.com/ory/docs/commit/706b5d6fcef61a77b44d268793f7655140ca1c2b


To reproduce the problem, list all of your active sessions (you can find your user ID under the console `https://console.ory.sh/projects/<project-id>/identities`:

Then call the sessions endpoint to list all of your active sessions

```shell
curl https://auth.terblanche.eu/admin/identities/<user-id>/sessions -H "Authorization: Bearer ory_pat_<token>" | jq

[
  {
    "id": "<session id>",
    "active": true,
    "expires_at": "2022-02-12T09:58:07.619762Z",
    "authenticated_at": "2022-02-11T09:58:07.619762Z",
    "authenticator_assurance_level": "aal1",
    "authentication_methods": [
      {
        "method": "password",
        "aal": "",
        "completed_at": "2022-02-11T09:58:07.619754282Z"
      }
    ],
    "issued_at": "2022-02-11T09:58:07.619762Z",
    "identity": {
      "id": "",
      "schema_id": "preset://email",
      "schema_url": "",
      "state": "active",
      "state_changed_at": "2022-02-10T13:57:53.668318Z",
      "traits": {
        "email": "email@example.com"
      },
      "verifiable_addresses": [
        {
          "id": "",
          "value": "email@example.com",
          "verified": false,
          "via": "email",
          "status": "sent",
          "created_at": "2022-02-10T13:57:53.705359Z",
          "updated_at": "2022-02-10T13:57:53.705359Z"
        }
      ],
      "recovery_addresses": [
        {
          "id": "",
          "value": "email@example.com",
          "via": "email",
          "created_at": "2022-02-10T13:57:53.712317Z",
          "updated_at": "2022-02-10T13:57:53.712317Z"
        }
      ],
      "metadata_public": null,
      "created_at": "2022-02-10T13:57:53.676513Z",
      "updated_at": "2022-02-10T13:57:53.676513Z"
    }
  }
]
```

Try call the `refresh` sessions endpoint:

```shell
curl -X PATCH "https://<project-url>/admin/sessions/<session-id>/refresh" -H "Authorization: Bearer ory_pat_<token>"    
404 page not found
```

`refresh` doesn't exist, only `extend` does. Try look for the `refresh` endpoint in our Kratos codebase 
https://github.com/ory/kratos/blob/master/session/handler.go#L63

Also in the documentation for our HTTP Api references, only extend exists:
https://www.ory.sh/docs/reference/api#operation/adminExtendSession
