### ISSUE TITLE
Update the example protect page login

### ISSUE THREAD

**Issue by kantum** [ory/docs#758]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

In the documentation, the example code does not work with a self-hosted kratos

https://www.ory.sh/docs/guides/protect-page-login/go#validate-and-login

I had to change this part of middleware.go
```
		// this will redirect the user to the managed Ory Login UI
			http.Redirect(writer, request, "/.ory/api/kratos/public/self-service/login/browser", http.StatusSeeOther)
```
to
```
		// this will redirect the user to the managed Ory Login UI
			http.Redirect(writer, request, "/.ory/login", http.StatusSeeOther)
```

It may be a good idea to update the documentation under the Self-Hosted Ory Kratos tab

### Reproducing the bug

Follow the instruction under of protect-page-login under the Self-Hosted Ory Kratos

### Version

v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
@Benehiko can you take a look when you have some time?
