### ISSUE TITLE
Go "protect a page" can simplify cookie code

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#761]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Go example uses string concatenation to construct the cookie header:

```
		// set the cookies on the ory client
		var cookies string
		for _, cookie := range request.Cookies() {
			cookies += cookie.String() + ";"
		}

		// check if we have a session
		session, _, err := app.ory.V0alpha2Api.ToSession(request.Context()).Cookie(cookies).Execute()
		if (err != nil && session == nil) || (err == nil && !*session.Active) {
			// this will redirect the user to the managed Ory Login UI
			http.Redirect(writer, request, "/.ory/api/kratos/public/self-service/login/browser", http.StatusSeeOther)
			return
		}
```

however, I think it should be possible to just pass the header down which would make the code easier:

```
		// check if we have a session
		session, _, err := app.ory.V0alpha2Api.ToSession(request.Context()).Cookie(r.Headers.Get('Cookie')).Execute()
		if (err != nil && session == nil) || (err == nil && !*session.Active) {
			// this will redirect the user to the managed Ory Login UI
			http.Redirect(writer, request, "/.ory/api/kratos/public/self-service/login/browser", http.StatusSeeOther)
			return
		}
```

or is there something I missed?

### Reproducing the bug

See above

### Version

master

**Comment by tomekpapiernik** [comment]
@Benehiko @gen1us2k 
I guess this is done, right? If so, please close the issue.

**Comment by gen1us2k** [comment]
Yep. You're right. Closing issue
