### ISSUE TITLE
Wrong jwt authenticator config example

### ISSUE THREAD

**Issue by newmanwang** [ory/docs#81]
In the `jwt` section from `Guides `> `api access rule` of oathkeeper doc, value of `require_audience` and `trusted_issuers`  field in example authenticator config not follow statement claimed above it:

The following rule allows requests to GET http://my-app/some-route if valid a JSON Web Token was provided and if that token has scope scope-a and scope-b, audience **aud-1** and was issued by **iss-1**. All configuration items are optional and ignored if left out.

```
{
    "id": "some-id",
    "upstream": {
        "url": "http://my-backend-service"
    },
    "match": {
        "url": "http://my-app/some-route",
        "methods": [
            "GET"
        ]
    },
    "authenticators": [{
        "handler": "jwt",
        "config": {
            "required_scope": ["scope-a", "scope-b"],
            "require_audience": ["scope-a", "scope-b"],
            "trusted_issuers": ["scope-a", "scope-b"],
        }
    }],
    /* ... */
}
```

**Comment by aeneasr** [comment]
Nice catch, would you mind creating a PR? :)

**Comment by newmanwang** [comment]
Sure! Pull request sent.
