### ISSUE TITLE
Document how to set up custom email templates using the Ory CLI

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#816]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We currently explain how to set up custom email templates here: https://www.ory.sh/docs/kratos/concepts/email-sms

### Describe your ideal solution

This should move to the main documentation, maybe into multiple guides, and explain how to use this feature in both self-hosted and ory cloud!

### Workarounds or alternatives

none

### Version

master

**Comment by tomekpapiernik** [comment]
We now have a cool, extensive doc on email templates :))
https://www.ory.sh/docs/kratos/emails-sms/custom-email-templates
