### ISSUE TITLE
Build a catalog of all Ory examples with filter/search

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#817]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, examples and community contributions are scattered across Ory's documentation. It is very difficult for someone new to find the page where these examples live.

### Describe your ideal solution

Gatsby has https://www.gatsbyjs.com/plugins

NextJS has https://nextjs.org/examples

We also need such an index page which is clearly visible and easy to find, and lists all the examples.

### Workarounds or alternatives

-

### Version

master

**Comment by BlueAcidFrog** [comment]
I like the idea of pushing the traffic to Github, this will allow us to move quickly on this and stay relevant & quick. Digital will come up with a draft version for the index page and will need your input @vinckr collecting all the example links. @DaydreamerUnicorn similar to CLI, please lets set up a doc that we can share with team to have all information central.

**Comment by gen1us2k** [comment]
AFAIK @vinckr had implemented something similar for the community projects. I think, we can apply it to the examples without any issues

**Comment by vinckr** [comment]
I have some idea how it should look and also gathered some material so I will make a draft for this in docusaurus. Will ping y'all in the draft PR.


All examples can be found here https://www.ory.sh/docs/ecosystem/community, here https://github.com/ory/examples and in the docs/blog.

**Comment by BlueAcidFrog** [comment]
@RinorG
