### ISSUE TITLE
sdk configuration documentation issue

### ISSUE THREAD

**Issue by curranjrobertson** [ory/docs#852]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

There is an error in the code in the guide, https://www.ory.sh/docs/guides/protect-page-login/expressjs which produces error code 401.
changing this:

var sdk = require('@ory/client')

var ory = new sdk.V0alpha2Api(
  new sdk.Configuration({
    baseUrl: '/.ory'
  })
)

to this:

const ory = new sdk.V0alpha2Api(
  new sdk.Configuration({
    basePath: '/.ory',
    baseOptions: {
      baseURL: 'http://localhost:4000/'
    }
  })
);

makes it work

### Reproducing the bug

git@github.com:curranjrobertson/express-server-demo.git
# To Run Code

# get express
mkdir your-project
cd your-project

npx express-generator
npm i

# get ory sdk
npm i --save @ory/client

#get ory cli
npm i --save @ory/cli

npm run dev
#new terminal
npm run proxy

# In browser
localhost:4000/login

#Login to ory

#redirect to home page

### Relevant log output

```shell
Request failed with status code 401
```

### Version

"@ory/cli": "0.1.32",     "@ory/client": "^0.0.1-alpha.181",

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Ory Cloud

**Comment by vinckr** [comment]
This has been fixed since 👍
