### ISSUE TITLE
Footer nav has lists

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#870]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

<img width="1156" alt="Bildschirmfoto 2022-06-15 um 11 58 31" src="https://user-images.githubusercontent.com/3372410/173800531-b2594908-7fe0-45fb-a6c6-31a61bbbbca8.png">

### Reproducing the bug

Probably a small CSS change

### Version

master

**Comment by himanshu-suman** [comment]
Hi @aeneasr  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by theshashankpal** [comment]
Hey @aeneasr, 
@himanshu-suman is going to Israel so he cannot contribute please assign this bug to me

**Comment by aeneasr** [comment]
Awesome! No need to assign the issue, just pick it up and make a PR :)))
