### ISSUE TITLE
Invalid RFC3339 timestamp example on API Design > Date Format

### ISSUE THREAD

**Issue by halostatue** [ory/docs#886]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The example given on [API Design > Date Format](https://github.com/ory/docs/blob/master/docs/ecosystem/api-design.md#date-format) does not seem to be a valid rfc3339 timestamp.

```json
{
  "created_at": "2006-01-02T15:04:05Z07:00"
}
```

Per [RFC3339 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), the ABNF indicates that the `time-offset` should be *either* `Z` *or* `time-numoffset`, which is `("+" / "-") time-hour ":" time-minute`. Therefore, the example should be one of the following:

- `{ "created_at": "2006-01-02T15:04:05Z" }` (UTC)
- `{ "created_at": "2006-01-02T15:04:05-0700" }` (Usually MST or PDT)
- `{ "created_at": "2006-01-02T15:04:05+0700" }` (Thailand, Cambodia, Krasnoyarsk, etc.)

### Reproducing the bug

n/a (This field does not seem correct for a documentation bug template.)

### Version

n/a (this field does not seem correct for documentation)

**Comment by aeneasr** [comment]
Great find, you're right! It should be

```
{
  "created_at": "2006-01-02T15:04:05+07:00"
}
```
