### ISSUE TITLE
Recovery documentation page broken?

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#891]
### Discussed in https://github.com/ory/kratos/discussions/2566

<div type='discussions-op-text'>

<sup>Originally posted by **jonnyijapan** July  4, 2022</sup>
If I open this link: https://www.ory.sh/docs/kratos/self-service/flows/account-recovery#recovery-for-server-side-browser-clients

It shows a page that looks like this. It looks like it might be broken, or some design isn't working. It looks like a dark blue background, with text that is dark brown/grey. The text is almost invisible, it's not easy to even spot the text.
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/278883/177181639-ba7caf33-d645-49e9-b87a-69605e632495.png">

If I do a cmd-a to select all text, the text becomes easier to see...
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/278883/177181892-7270273f-e815-45ce-8f3d-f01ac712ead5.png">
</div>

**Comment by jonas-jonas** [comment]
I also have a similar issue with darkmode enabled on the recovery documentation [1]. Without darkmode it looks good again.

[1]
 
<img width="2560" alt="Screenshot 2022-08-05 at 11 08 31" src="https://user-images.githubusercontent.com/5540255/183044219-94eb9398-a338-4d9a-8667-3d438e5edd26.png">

**Comment by vinckr** [comment]
We probably just have to tweak the mermaid template a bit 
https://github.com/sjwall/mdx-mermaid/pull/21

This PR will (hopefully?) fix it: https://github.com/facebook/docusaurus/pull/7490 
So the question is if we wait for this or make a custom mermaid style for darkmode before.

**Comment by vinckr** [comment]
Hm it seems the mermaid blocks have the same styling as "info" admonissions. 
if we can override `--ifm-color-info-contrast-background` just for the mermaid graphs that would fix it.

**Comment by tomekpapiernik** [comment]
Not valid anymore after merging 
https://github.com/ory/docs/pull/995
