### ISSUE TITLE
Versioning scheme and documentation issues.

### ISSUE THREAD

**Issue by vangheem** [ory/docs#92]
I'm rather confused on versioning scheme and release cycle for ory ecosystem of products.

Just yesterday I was working with keto and had been deploying with 1.0.0 tagged releases but today it seems like all the docs are completely different and now they're based off a 0.2.2 release.

See tags here: https://hub.docker.com/r/oryd/keto/tags

See docs here: https://www.ory.sh/docs/keto/sdk/api

Did the wrong docs get built for a sandbox/unstable release?

Or what would be recommended to work off of?

Are there docs related to this?

**Comment by aeneasr** [comment]
Yes, this is very well documented: https://www.ory.sh/docs/ecosystem/versioning#november-2018-change

Consider subscribing to the newsletter so you don't miss important updates like these!

Sorry for the confusion, but it's all explained in the docs.

**Comment by vangheem** [comment]
Sounds good. Thanks you.
