### ISSUE TITLE
Add guide to explain how to use Apple Pass Keys

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#949]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We support pass keys already, here is a guide I wrote: https://github.com/ory/kratos/discussions/2662#discussioncomment-3380221

### Describe your ideal solution

Use the guide and explain it a bit better in a dedicated documentation file under "passwordless".

### Workarounds or alternatives

-

### Version

master

**Comment by tomekpapiernik** [comment]
https://www.ory.sh/docs/kratos/passwordless/passkeys
