### ISSUE TITLE
Be more explicit about Cloud email recovery/verification flow behaviour on localhost environment

### ISSUE THREAD

**Issue by Benehiko** [ory/docs#957]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Right now when users integrate with Ory through local testing using the Ory proxy/tunnel, Kratos will send the email to the User with the project slug as and ory domain as the link. This is expected, however, can be confusing since the User is integrating and testing using the Ory tunnel on `localhost:4000`.

### Describe your ideal solution

Make it explicit why this is happening and how it will look in Production with and without CNAME.

### Workarounds or alternatives

None

### Version

latest

**Comment by aeneasr** [comment]
We will soon remove the magic link strategy and replace it with a domain-free code.
