### ISSUE TITLE
Custom UI docs need love

### ISSUE THREAD

**Issue by Benehiko** [ory/docs#961]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

It's difficult to understand how to transition from local environment to staging and then production on https://www.ory.sh/docs/guides/bring-your-user-interface.

This ties in with https://github.com/ory/docs/issues/873

### Describe your ideal solution

We need to describe how relative URLs work with these settings and how we can setup production and staging environments. 

### Workarounds or alternatives

None

### Version

latest

**Comment by Benehiko** [comment]
The solution of configuring relative paths for multiple "test" environments are difficult to grasp when using the `ory tunnel`/`ory proxy`. In the case of such a use case it becomes tedious to setup as creating a CNAME entry per environment wouldn't be optimal.

The options are:
1. Create a project per environment (localhost, test dev, staging, production)
2. Use a reverse proxy to group the test environments (local, test dev and staging) to handle relative paths under the same host (the reverse proxy host).

This becomes more tedious to setup than the actual production environment.

**Comment by vinckr** [comment]
while the docs still need love (who doesn't :wink:), custom UI has had a lot of improvements.
closing this to declutter the backlog a bit.
