### ISSUE TITLE
Reference configuration is broken

### ISSUE THREAD

**Issue by cjhines** [ory/docs#987]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

https://www.ory.sh/docs/oathkeeper/reference/configuration

### Reproducing the bug

https://www.ory.sh/docs/oathkeeper/reference/configuration

### Version

1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Other

**Comment by tomekpapiernik** [comment]
Hey @cjhines , not sure what you mean by "it's broken"? I can access the config page just fine. Care to elaborate?

**Comment by aeneasr** [comment]
I believe we fixed it since!
