### ISSUE TITLE
Social Sign In SEO result ends up in orphan page

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#988]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When searching for "Social Sign In Ory", I end up at this page with the first search result: https://www.ory.sh/docs/concepts/social-sign-in

<img width="717" alt="Bildschirmfoto 2022-09-13 um 11 11 30" src="https://user-images.githubusercontent.com/3372410/189861718-b02f86d9-04dd-40d2-8d01-e342e25cd997.png">

Please remove the doc and redirect people to: https://www.ory.sh/docs/kratos/social-signin/overview

### Reproducing the bug

https://www.google.com/search?client=safari&rls=en&q=social+sign+in+ory&ie=UTF-8&oe=UTF-8

### Version

master

**Comment by tomekpapiernik** [comment]
https://github.com/ory/docs/pull/1056
